### ISSUE TITLE
[feat] Desktop Wallet

### ISSUE THREAD

**Issue by shanimal08** [tari-project/universe#1577]
# Tari Universe: Transaction sending & receiving

[**Figma**](https://www.figma.com/design/Tyh0UcWVo44z66gYHd0TBs/Tari-Universe-Planning-%26-Wires?node-id=5954-10088&p=f&t=aPbhIkeyO6YWD3bB-0)

## Problem
The current wallet implementation within Tari Universe is view-only. Users cannot send or receive transactions directly from the application. To enhance functionality, we need to introduce sending and receiving transactions while maintaining security constraints. 

## Solution
Expand the existing wallet functionality to support sending and receiving transactions while preserving the view-only security model. This will be achieved by utilizing one-sided payments from a recovered wallet, ensuring the live wallet does not store spend keys.

### Plan 1: Recovering a Wallet from Seeds (Selected Solution)
- The wallet will be fully recovered from its seed phrase.
- Once recovered, the wallet will have access to both view and spend keys.
- A one-sided payment transaction will be executed from this fully recovered wallet.
- This ensures the wallet has all necessary keys and functions correctly.
- ~~Downside: Recovery time can be significant, depending on wallet history.~~
- [Reference Section 8](https://tari.com/lessons/09_adding_tari_to_your_exchange#section-8-performing-withdrawals)
- **Comment:** Because the wallet and base node communicate over TCP, recovery time should in fact be fast. Recovery is only slow when done over TOR.

### Plan 2: Cloning the Existing Wallet and Recovering with Existing Data
- Clone the existing wallet data to attempt a faster recovery.
- Execute wallet commands with the spend key from the cloned wallet.
- Issue: View-only wallets contain only about 99% of the required keys.
- As a result, the recovered wallet will not function properly.
- **Conclusion:** This plan is flawed and will not work as intended. **We will not move forward with this plan.**

### Plan 3: Using a View-Key Wallet with External Signing
1. The **view-key wallet** operates within Tari Universe (TU).
2. TU requests the view-key wallet to construct a transaction to spend 100 XTM to PersonA.
3. The view-key wallet creates a structured JSON containing UTXO details needed for transaction creation.
4. TU calls `wallet_signer.exe` or `console_wallet.exe` with the private key from secure storage and the JSON data.
5. `wallet_signer.exe` or `console_wallet.exe` uses the private key to generate the remaining components of the transaction and either:
   - Submits it directly to the base node, or
   - TU submits it to the base node.

This approach ensures that the view-key wallet does not hold spend keys while enabling transaction execution securely.

**Concern:** My concern about using the console wallet is that we need to add a ton of exceptions to make it work outside of the normal route, it would be better to write a new application for that. Apart from using the code from the transaction builder and key manager, it's not going to do anything that the current console wallet does, and the way it's going to use the transaction builder + key manager is also going to be completely different.

**Conclusion:** This plan is sound, but complex, with many additional requirements. **We will not move forward with this plan.**

### Plan 4: Using a Key Manager for Transaction Construction
1. TU requests the wallet for UTXOs sufficient to spend X (potentially using only public info).
2. TU boots up a key manager using the spending seed words.
3. TU uses the provided UTXOs along with the Tari Core transaction construction library to create a transaction.
4. TU submits the transaction to the base node (leveraging existing code for this process).

This method ensures the view-only wallet remains secure while leveraging a separate key manager for transaction signing and submission.

**Conclusion:** This plan is sound, but complex, with many additional requirements. **We will not move forward with this plan.**

---

#### Sidebar Refactor:
- Add minimized state for better user experience.
- Update Sidebar Component:
  - New Trade CTA offering Send, Receive, and Swap options.
  - UI for these options could be either:
    - A drawer component
    - An overlay component
- Expanded State Additions:
  - Wallet Connect CTA (opens wallet connect modal)
  - Swap Transaction Interface
  - Success state for transaction confirmations

#### New Modal Components:
- Dedicated Wallet Modal with the following tabs:
  - **Send**: Transaction initiation UI
  - **Receive**: Display wallet address & QR code
  - ~~**Swap**: Interface for asset swapping~~
  - **History**: Displays both rewards and standard transactions (sent & received)

#### Rewards Drawer Updates:
- Show both sent and received transactions

### Backend components
- A managed process for triggering and monitoring the wallet
  - Recovery
  - Funds verification
  - Sending
  - Removal and cleanup

---

### Transaction Flow:
- Sending transactions will **not** be handled by the running view-only wallet.
- Instead, a one-sided payment will be executed from a **recovered wallet**.
- The recovered wallet needs an ensured cleanup and can not be left behind after the transaction is finished (completed, or failed)
- If we can find some kind of secure container to create the recovered wallet in that would be a benefit

### Security Considerations:
- The live wallet remains view-only, preventing third-party attack risks.
- The spend key is only used within the recovered wallet process.

---

## Risks & Concerns
1. **Wallet Recovery Time:**
   - Recovery can take significant time depending on wallet history.
   - ~~Potential optimizations include snapshotting wallet state.~~

---

## Appetite
- **Timeframe:** 2 weeks
- **Focus:** Achieve basic send/receive functionality while maintaining security constraints

---

## No-Gos
- **Hot Swaps or Other Platform Integrations:**
  - No integrations with external platforms or hot swap mechanisms will be supported.
- **Interactive Transactions:**
  - All transactions must be **one-sided payments**.
  - No interactive transaction protocols will be supported.

---

## Next Steps
1. Finalize UI/UX design decisions (drawer vs. overlay, modal structure).
2. Review solution for technical feasability.

**Comment by SWvheerden** [comment]
FYI
the current view only wallet in TU can receive funds

All you need is the one-sided only address from the wallet. You can ask the grpc for that.

**Comment by brianp** [comment]
> the current view only wallet in TU can receive funds

Absolutely worth noting. I overlooked writing this as "I knew" 🙃 

The majority of this functionality is around the ability to send. Receiving is mostly filtering, and display from our existing wallet.

**Comment by mmrrnn** [comment]
Q: How do we actually define whether wallet is view or spendable?
A:
* We define spendable wallet by **not** passing any option
* We define view-only wallet by passing `--spend-key` and `--view-private-key`. it needs the private view key and public spend key to verify and scan for utxos.

**Comment by mmrrnn** [comment]
It takes about 15sec to connect to the base node and:
`Recovery complete! Scanned 9445 blocks in 7.33s (1288.72 blocks/s), Recovered 11 outputs worth 152533.716166 T`

**Comment by mmrrnn** [comment]
Note: **STILL EDITED**

Steps from the frontend perspective:
1. Define **one-sided** Tari Address of the recipient - we should validate whether it is **one-sided** address on the specific network
2. Define amount - we need to validate all possible cases: "1000000", "22T" etc.
5. Setup listener for the transaction result event 
6. Call `send-one-sided-to-stealth-address` command
7. Handle success/error result

**Comment by brianp** [comment]
> Recovery complete! Scanned 9445 blocks in 7.33s (1288.72 blocks/s), Recovered 11 outputs worth 152533.716166 T

This is not terrible. Let's make sure the wallet connects to the local base node over TCP and we may see it connect faster.

---

There's also two trains of thought for functionality:
1. For security we use a 1-time password on each wallet recovered to perform a tx. This ensures the wallet is harder to steal and make use of.

Alternatively

2. We keep the password for this wallet in secure storage (along with the seed words etc) and this wallet can be occasionally synced to ensure faster future transactions. 

For now, I'm inclined to go with option 1. as it keeps the process simpler. I'm open to opinions on the topic.

**Comment by mmrrnn** [comment]
Note: **STILL EDITED**

From the backend perspective:
1. Frontend calls `send-one-sided-to-stealth-address` commands with address, amount and optional payment id(message)
2. We spawn process instance and proceed with:
a) Recover wallet from passed seed words
b) Sync wallet to ensure validation process is completed
c) call `SendOneSidedToStealthAddress`
*Currently we need to call 3 separate commands(It's not the safest practice since we expose our args until the whole process is finished and all related data is cleared - password etc) or chain them using "&&"(error handling is quite challenging here - I'll use this solution for the 1st iteration). The best solution is to implement additional method for minotari_console_wallet in the core repo(we'll do this for the 2nd iteration)*

**Comment by shanimal08** [comment]
### UI update


FYI: i've updated my [PoC section in the figma](https://www.figma.com/design/Tyh0UcWVo44z66gYHd0TBs/Tari-Universe-Planning-%26-Wires?node-id=6511-12629&t=EQPdh4qZxY3fxrS1-0) - just using screenshots cos designing is hard:(

here's an updated video. 

today i just simplified the transaction history list UI to match the wip designs better, AND reintroduced it to the Mining View sidebar so we can still hit replay + share etc (there is a lil section like this in the designs), also moved the Wallet View sidebar to the left bd the fancy one on the right hand side was giving me a headache. 

i do need to make some adjustments to the animation now that `@tari-project/tari-tower` has gone in:p since the canvas offset is a little harder to manipulate, so ignore that ugly alignment for now hehe. 


@marcinpapiez pls ping me when you open your PR with the BE, i still have a bunch of UI components to put together, but would be good to hook them up to something as soon as i can so i don't build them badly xD 

cc @sprucetree

**Comment by mmrrnn** [comment]
Summary of the discussion between SW and me
-- 

* **One-sided** transactions are marked as "completed" once broadcasted and never appear as "pending" in the database.
* It's recommended keeping gRPC off for the spendable wallet for better security.
* The view-only wallet only recognizes sent transactions once they are mined and included in a block.
* We can't import spendable wallet's transactions directly into the view wallet due to key linking issues; the view wallet should scan for transactions on its own. 
* There is no way to pass broadcasted transactions to the view wallet since all related data is removed along with the spendable wallet(We could wait until tx is mined but it would require grpc enabled on a spendable wallet which is bad). Transaction ID is also not useful since it is only for local use and not transmitted on the blockchain
* For the first iteration, we consider using the amount and destination address to identify these transactions and display broadcasted-mocked transaction, but this could cause confusion if the same amount is sent multiple times. Another issue is that it's uncertain if the transaction will be included in the next block. 

cc @brianp @SWvheerden @shanimal08

**Comment by shanimal08** [comment]
# Outstanding/needs to be notes

### FE

- complete UI match to finalised designs (designs still TBC)
- before designs are confirmed:
  - move version chip (conflicts with new twitter banner)
  - base/emoji address toggle on `Receive` tab
- MAYBE add a timeout to refresh txs if BE monitoring won't be available soon (prefer not)

### BE 
_(outstanding from a FE point of view, there is likely more from an overall view)_

- pending transactions monitoring

**Comment by mmrrnn** [comment]
Update:
----
* I implemented a mocked transaction ui that is displayed until we fetch the actual transaction once it has been mined.
![Image](https://github.com/user-attachments/assets/b95abd26-2113-4ff6-8afe-0731bad8c239)

Another steps are mainly error handling:
----
1) In minotari_console_wallet, we should return excess sig(sig and public nonce) as a `send_one_sided_to_stealth_address` response. It's currently only way to identify a pending transaction from the mempool.
2) Use excess sig to call `get_tx_state`. Response from the pending tx: `TransactionStateResponse { result: Mempool }`. We could also use `stream_transaction_events` to listen on `TransactionMinedUnconfirmed` events.
3) We should improve error handling: timeout? handle some error codes etc, maybe retries - it should be investigated
4) We need to persist info about pending transactions

**Comment by peps** [comment]
Changes based on UI feedback: 

**Done:**

- Set the Wallet Sidebar "open" by default on initial load
- The arrow icon sometimes overlaps with the cube icon in the sidebar toggle. ( currently cant reproduce this )

**WIP:**

- Auto Focus the sender's address field on load
- Add focus state to the fields
- Truncate the wallet address like "XXXXXX...XXXXXX" when the field is not focused

**Needs discussion:**

- Remove the payment id field from the send UX 

**Questions:**

- Add green checkmark icon when a valid address is added 

do we need to call an API to validate the address? Or can it just be a front end validation check?

**Comment by brianp** [comment]
> Add green checkmark icon when a valid address is added
do we need to call an API to validate the address? Or can it just be a front end validation check?

@mmrrnn will add a `check_address_for_one_sided` function to validate the address. You can mock the request for now and we'll fill it in after. 

> Remove the payment id field from the send UX

Feel free to make it pretty, but the payment id field stays.

**Comment by peps** [comment]
Here's what's done in today's UI update:

1. Made Sidebar "open" by default
2. Simplified arrow logic and animation so it doesn't bug out.
3. add autoFocus to Tari Wallet Address field
4. Flipped Address and Message fields
5. Refactor / remove the Tabs component in favor of a "Sections" structure for simplicity. 
6. Updated overall style to better match designs ( still not perfect )
7. Truncate the address field when the field is blurred to "XXXXXX...XXXXXX"
8. Added error colors to the Send fields ( still improvements can be made to the display of the error text here )

Tomorrow ill add the address verification checkmark and continue with overall polish.

**Comment by peps** [comment]
Today's UI improvements for the desktop wallet UI. 

1. Sidebar closed by default, open after setup is complete
2. Added checkbox icon to the address field
3. Integrated address field validation with checkbox
4. Suppressed validation if the address field is blank, this should fix the issue needing to click the "Back" button twice. 
5. Fixed a bug where the user's address on the History section had capitalization styles applied. 
6. Various little style tweaks along the way

This should complete all of the feedback, except for the new designs that were also discussed in that thread.

**Comment by mmrrnn** [comment]
We also need an amount validation

**Comment by peps** [comment]
> [@Possum](https://github.com/Possum) re. the history list -
> 
> it is no longer minimised then opened so the "win" counter has been removed since it doesn't work with the always opened history list. in the designs there is a little `new` tag though -
> 
> ![Image](https://github.com/user-attachments/assets/91b7b517-cc36-40e9-88f6-1d81752101cd)
> 
> how is this meant to work exactly? when does a history item cease to be `new`? 😅
> 
> cc [@brianp](https://github.com/brianp)

Unless someone else chimes in, I recommend adding the "new" tag to the 3 latest entries for the user's current session. So when the user first loads the app, none of them have the tag. Then as they start mining, the new entries added will have it, up to 3 ( or 5, whichever looks better ). 

On top of that we could add a timer check, for example, only entries less than 1 hour old can have the tag. But I think the above should be a good start.

**Comment by brianp** [comment]
@shanimal08 

Issue:
When a user enters 1000 in the TX amount input field, the transaction is submitted as 1000µT (micro mino Tari), instead of the expected 1000T (mino Tari).

Expected Behaviour:
User-entered values should be interpreted as whole Tari units (T), not micro Tari (µT).
For reference: 1,000,000 µT = 1 T

Suggested Fix:
Use the MinoTari and MicroMinoTari struct types to correctly interpret and convert the user input into Tari. These types handle conversions and rounding appropriately.

Nuance:
Users should be able to enter decimals up to 6 places of precision. Ex: 0.000006. Which is 0.000006T = 6uT

Steps to Reproduce:

-     Open the TU desktop wallet
-     Enter 1000 as the TX amount
-     Submit the transaction
-     **Currently:** Observe that the amount sent is 1000µT instead of 1000T
-     **Expected:** The amount should be 1000T

**Comment by brianp** [comment]
Closing as this feature has been shipped in v1.0.0 and any further refinements will be made in new issues. 

Thanks team!
